language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=django==1.4.5 --use-mirrors

install:
  - pip install $DJANGO
  - pip install -r requirements/travis-ci.txt --use-mirrors

script:
  - python runtests.py

branches:
    only:
        - master

matrix:
  include:
    - python: "2.6"
      env: DJANGO=django==1.5.10 --use-mirrors
    - python: "2.7"
      env: DJANGO=django==1.6.6 --use-mirrors
    - python: "2.7"
      env: DJANGO=django==1.7 --use-mirrors
    - python: "3.2"
      env: DJANGO=django==1.7 --use-mirrors
    - python: "3.3"
      env: DJANGO=django==1.7 --use-mirrors
    - python: "3.4"
      env: DJANGO=django==1.7 --use-mirrors
